### ISSUE TITLE
local: Hippo sqlite error

### ISSUE THREAD

**Issue by lann** [fermyon/installer#36]
The `hippo.nomad` task is failing to start (Arch Linux):

`alloc/logs/hippo.stdout.0`:
```
      An error occurred while migrating or seeding the database.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
         at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
         at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
         at Microsoft.Data.Sqlite.SqliteConnection.Open()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
         at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
         at Program.<Main>$(String[] args) in /home/runner/work/hippo/hippo/src/Web/Program.cs:line 134
```

**Comment by lann** [comment]
Changing the database driver to `inmemory` is a workaround for me.

**Comment by bacongobbler** [comment]
@gogeterobert and I paired this morning on the local installer and hit this issue along with a few others. We believe this stems from some form of permission issue on nomad's side. We can also confirm changing the database driver to `inmemory` was a workaround for the database driver, but we still encountered issues with the nomad job status API as well as spin/wasmtime caching issues.

Going to look further into this today.
